[package]
name = "langextract"
version = "0.1.0"
edition = "2024"
authors = ["dalei <guoyunlei@live.com>"]
description = "A Rust library for extracting structured data from unstructured text using Large Language Models (LLMs), featuring precise source attribution and interactive visualization capabilities."
license = "MIT"

[dependencies]
